name: arcadiachorale
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Arcadia Chorale
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030408'
    - '#394315'
    - '#acd2fe'
    - '#6b7352'
    - '#d2a997'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
